# Generated by Django 5.1.4 on 2026-05-15 10:57

import apps.catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, help_text='Which page/section', max_length=64)),
            ],
            options={
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Spiti Valley 6D/5N'", max_length=120)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated if left blank', max_length=140, unique=True)),
                ('category', models.CharField(choices=[('trek', 'Himalayan Trek'), ('road', 'Road Trip'), ('weekend', 'Weekend Getaway'), ('intl', 'International'), ('backpack', 'Backpacking'), ('luxury', 'Luxury')], default='trek', max_length=16)),
                ('short_description', models.CharField(blank=True, help_text='One-line teaser shown on cards', max_length=240)),
                ('long_description', models.TextField(blank=True, help_text='Full description for the detail page')),
                ('price', models.PositiveIntegerField(help_text='Base price in INR')),
                ('duration_days', models.PositiveSmallIntegerField(default=0)),
                ('duration_nights', models.PositiveSmallIntegerField(default=0)),
                ('hero_image', models.ImageField(blank=True, upload_to=apps.catalog.models.package_image_path)),
                ('brochure_pdf', models.FileField(blank=True, help_text='Itinerary PDF — uploads to your configured storage backend (R2 / S3 / etc).', upload_to=apps.catalog.models.package_brochure_path)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text="Show in 'Featured' on home")),
                ('coming_soon', models.BooleanField(default=False)),
                ('display_order', models.PositiveSmallIntegerField(default=100, help_text='Lower numbers shown first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'is_featured'], name='catalog_pac_is_acti_152aec_idx'), models.Index(fields=['category'], name='catalog_pac_categor_8fd4e5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('slots_total', models.PositiveSmallIntegerField(default=20)),
                ('slots_booked', models.PositiveSmallIntegerField(default=0)),
                ('price_override', models.PositiveIntegerField(blank=True, help_text='If set, overrides Package.price for this batch', null=True)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('status', models.CharField(choices=[('open', 'Open'), ('filling', 'Filling fast'), ('waitlist', 'Waitlist only'), ('closed', 'Closed')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='catalog.package')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
